### ISSUE TITLE
make histograms strict in under/overflows

### ISSUE THREAD

**Issue by cspollard** [Shimuuar/histogram-fill#6]
Hello,

First thanks very much for this library; it's been very useful for me.

I am seeing what I believe is a space leak coming from the under/overflows of Histograms. I suppose it's because Maybe and (a, a) are lazy in their objects. Does this sound feasible? Could we internally store the under/overflows in a stricter structure?

Chris

PS: I am happy to give this a go myself if you think it makes sense.

**Comment by Shimuuar** [comment]
This is certainly possible. I changed representation and will make a release tomorrow.

**Comment by Shimuuar** [comment]
Uploaded as 0.8.5.0 with other fixes/enhancemns

**Comment by cspollard** [comment]
Thanks!
